<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
    <PackageReference Include="TUnit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Configuration.Persistence.AspNetCore\Configuration.Persistence.AspNetCore.csproj" />
    <ProjectReference Include="..\Configuration.Persistence.TestKit\Configuration.Persistence.TestKit.csproj" />
  </ItemGroup>

</Project>
