namespace Kritikos.Configuration.Persistence.Interceptors.SaveChanges;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;

using Kritikos.Configuration.Persistence.Contracts;
using Kritikos.Configuration.Persistence.Contracts.Behavioral;
using Kritikos.Configuration.Persistence.Entities;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.Diagnostics;

/// <summary>
/// Saves <typeparamref name="TAuditRecord"/> trails in the same <typeparamref name="TContext"/> or a different one as long as it implements <see cref="IAuditTrailDbContext{TAudit}"/>.
/// Entities to be audited should implement <see cref="ITraceableAudit"/>.
/// </summary>
/// <typeparam name="TAuditRecord">Overridable entity that contains audit fields, should extend <see cref="AuditRecord"/>.</typeparam>
/// <typeparam name="TContext">The type of the <see cref="DbContext"/> to save into.</typeparam>
/// <remarks>
/// <typeparamref name="TAuditRecord"/> can not implement <see cref="ITraceableAudit"/>, otherwise <see cref="SavingChangesAsync"/> and/or <see cref="SavingChanges"/> would recursively call themselves.
/// Entries whose keys are generated by the store are held between saving and saved, so an instance must not serve concurrent saves. Register it per <see cref="DbContext"/> instance rather than as a singleton.
/// </remarks>
public class AuditTrailSaveChangesInterceptor<TAuditRecord, TContext> : SaveChangesInterceptor
  where TAuditRecord : AuditRecord, new()
  where TContext : DbContext, IAuditTrailDbContext<TAuditRecord>
{
  private readonly bool recordUnchangedProperties;
  private readonly JsonSerializerOptions serializerOptions;
  private readonly TimeProvider timeProvider;
  private readonly TContext? context;

  private TContext? pendingContext;
  private List<AuditEntry> transient = [];

  /// <summary>
  /// Initializes a new instance of the <see cref="AuditTrailSaveChangesInterceptor{TAuditRecord,TContext}"/> class that will record audit trails in the same context as the actual entities.
  /// </summary>
  /// <param name="recordUnchangedProperties">If true, records only delta changes between states, otherwise records the complete current and previous state.</param>
  /// <param name="serializerOptions">Custom options for <see cref="JsonSerializer"/> to handle specific cases during auditing.</param>
  /// <param name="timeProvider">The <see cref="TimeProvider"/> supplying <see cref="AuditRecord.CreatedAt"/>, defaulting to <see cref="TimeProvider.System"/>.</param>
  /// <exception cref="NotSupportedException"><typeparamref name="TAuditRecord"/> extends <see cref="ITraceableAudit"/>.</exception>
  public AuditTrailSaveChangesInterceptor(
    bool recordUnchangedProperties = true,
    JsonSerializerOptions? serializerOptions = null,
    TimeProvider? timeProvider = null)
  {
    if (typeof(ITraceableAudit).IsAssignableFrom(typeof(TAuditRecord)))
    {
      throw new NotSupportedException($"{typeof(TAuditRecord).Name} cannot be {nameof(ITraceableAudit)}.");
    }

    this.recordUnchangedProperties = recordUnchangedProperties;
    this.serializerOptions = serializerOptions ?? JsonSerializerOptions.Default;
    this.timeProvider = timeProvider ?? TimeProvider.System;
  }

  /// <summary>
  /// Initializes a new instance of the <see cref="AuditTrailSaveChangesInterceptor{TAuditRecord,TContext}"/> class that will record audit trails in the passed instance of <paramref name="context"/>.
  /// </summary>
  /// <param name="context">The <see cref="DbContext"/> to save <see cref="AuditRecord"/> to.</param>
  /// <param name="recordUnchangedProperties">If true, records only delta changes between states, otherwise records the complete current and previous state.</param>
  /// <param name="serializerOptions">Custom options for <see cref="JsonSerializer"/> to handle specific cases during auditing.</param>
  /// <param name="timeProvider">The <see cref="TimeProvider"/> supplying <see cref="AuditRecord.CreatedAt"/>, defaulting to <see cref="TimeProvider.System"/>.</param>
  /// <exception cref="ArgumentNullException"><paramref name="context"/> is null.</exception>
  /// <exception cref="NotSupportedException"><typeparamref name="TAuditRecord"/> extends <see cref="ITraceableAudit"/>.</exception>
  public AuditTrailSaveChangesInterceptor(
    TContext context,
    bool recordUnchangedProperties = true,
    JsonSerializerOptions? serializerOptions = null,
    TimeProvider? timeProvider = null)
    : this(recordUnchangedProperties, serializerOptions, timeProvider)
  {
    ArgumentNullException.ThrowIfNull(context);

    this.context = context;
  }

  /// <inheritdoc />
  /// <exception cref="InvalidOperationException">No <typeparamref name="TContext"/> was supplied and the saving context is not a <typeparamref name="TContext"/>.</exception>
  public override InterceptionResult<int> SavingChanges(DbContextEventData eventData, InterceptionResult<int> result)
  {
    ArgumentNullException.ThrowIfNull(eventData);

    AuditTrackedEntries(eventData);

    return base.SavingChanges(eventData, result);
  }

  /// <inheritdoc />
  /// <exception cref="InvalidOperationException">No <typeparamref name="TContext"/> was supplied and the saving context is not a <typeparamref name="TContext"/>.</exception>
  public override ValueTask<InterceptionResult<int>> SavingChangesAsync(
    DbContextEventData eventData,
    InterceptionResult<int> result,
    CancellationToken cancellationToken = default)
  {
    ArgumentNullException.ThrowIfNull(eventData);

    AuditTrackedEntries(eventData);

    return base.SavingChangesAsync(eventData, result, cancellationToken);
  }

  /// <inheritdoc />
  public override int SavedChanges(SaveChangesCompletedEventData eventData, int result)
  {
    var saveResult = base.SavedChanges(eventData, result);

    if (transient.Count != 0 && pendingContext is { } auditContext)
    {
      var pending = transient;
      transient = [];
      pendingContext = null;
      UpdateTemporaryProperties(pending, auditContext);
      auditContext.SaveChanges();
    }

    return saveResult;
  }

  /// <inheritdoc />
  public override async ValueTask<int> SavedChangesAsync(
    SaveChangesCompletedEventData eventData,
    int result,
    CancellationToken cancellationToken = default)
  {
    var saveResult = await base.SavedChangesAsync(eventData, result, cancellationToken);

    if (transient.Count != 0 && pendingContext is { } auditContext)
    {
      var pending = transient;
      transient = [];
      pendingContext = null;
      UpdateTemporaryProperties(pending, auditContext);
      await auditContext.SaveChangesAsync(cancellationToken);
    }

    return saveResult;
  }

  /// <inheritdoc />
  public override void SaveChangesFailed(DbContextErrorEventData eventData)
  {
    transient = [];
    pendingContext = null;
    base.SaveChangesFailed(eventData);
  }

  /// <inheritdoc />
  public override Task SaveChangesFailedAsync(DbContextErrorEventData eventData, CancellationToken cancellationToken = default)
  {
    transient = [];
    pendingContext = null;
    return base.SaveChangesFailedAsync(eventData, cancellationToken);
  }

  private void AuditTrackedEntries(DbContextEventData eventData)
  {
    if (eventData.Context is not { } savingContext)
    {
      return;
    }

    var auditContext = context ?? savingContext as TContext
      ?? throw new InvalidOperationException(
        $"No {typeof(TContext).Name} was supplied to {GetType().Name} and the saving context is not a {typeof(TContext).Name}.");

    var entries = savingContext.ChangeTracker
      .Entries<ITraceableAudit>()
      .Where(x => x.State is not EntityState.Detached and not EntityState.Unchanged)
      .ToList();

    if (entries.Count != 0)
    {
      CreateAuditEntries(entries, auditContext);
    }
  }

  private void CreateAuditEntries(List<EntityEntry<ITraceableAudit>> entries, TContext auditContext)
  {
    // Stamped once so the trail of a save shares an instant, including the entries held back for store generated keys.
    var now = timeProvider.GetUtcNow().UtcDateTime;
    var auditEntries = new List<AuditEntry>(entries.Count);
    foreach (var entry in entries)
    {
      var table = entry.Metadata.GetTableName()
        ?? throw new InvalidOperationException(
          $"{entry.Metadata.DisplayName()} is not mapped to a table and cannot be audited.");

      var audit = new AuditEntry { TableName = table, State = entry.State, CreatedAt = now };
      auditEntries.Add(audit);
      foreach (var property in entry.Properties)
      {
        if (property.IsTemporary)
        {
          audit.TemporaryProperties.Add(property);
          continue;
        }

        if (property.Metadata.IsPrimaryKey())
        {
          audit.KeyValues.Add(property.Metadata.Name, property.CurrentValue!);
          continue;
        }

        switch (entry.State)
        {
          case EntityState.Added:
            audit.NewValues.Add(property.Metadata.Name, property.CurrentValue!);
            break;

          case EntityState.Deleted:
            audit.OldValues.Add(property.Metadata.Name, property.OriginalValue!);
            break;

          case EntityState.Modified:
            if (recordUnchangedProperties || property.IsModified)
            {
              audit.NewValues.Add(property.Metadata.Name, property.CurrentValue!);
              audit.OldValues.Add(property.Metadata.Name, property.OriginalValue!);
            }

            break;
          case EntityState.Detached:
          case EntityState.Unchanged:
          default:
            break;
        }
      }
    }

    var permanent = auditEntries.Where(x => x.TemporaryProperties.Count == 0).Select(x => x.ToAuditRecord(serializerOptions)).ToList();
    auditContext.AuditRecords.AddRange(permanent);

    // Entries with store-generated keys cannot be serialized until the save completes.
    transient.AddRange(auditEntries.Where(x => x.TemporaryProperties.Count != 0));
    pendingContext = transient.Count != 0
      ? auditContext
      : null;
  }

  private void UpdateTemporaryProperties(List<AuditEntry> entries, TContext auditContext)
  {
    foreach (var entry in entries)
    {
      foreach (var property in entry.TemporaryProperties)
      {
        if (property.Metadata.IsPrimaryKey())
        {
          entry.KeyValues.Add(property.Metadata.Name, property.CurrentValue!);
        }
        else
        {
          entry.NewValues.Add(property.Metadata.Name, property.CurrentValue!);
        }
      }

      auditContext.AuditRecords.Add(entry.ToAuditRecord(serializerOptions));
    }
  }

  private class AuditEntry
  {
    private const string Empty = "{}";

    public string TableName { get; init; } = string.Empty;

    public EntityState State { get; init; }

    public DateTime CreatedAt { get; init; }

    public Dictionary<string, object> KeyValues { get; } = [];

    public Dictionary<string, object> OldValues { get; } = [];

    public Dictionary<string, object> NewValues { get; } = [];

    public List<PropertyEntry> TemporaryProperties { get; } = [];

    public TAuditRecord ToAuditRecord(JsonSerializerOptions serializerOptions)
      => new()
      {
        CreatedAt = CreatedAt,
        Table = TableName,
        Key = JsonSerializer.Serialize(KeyValues, serializerOptions),
        OldValues = OldValues.Count != 0
          ? JsonSerializer.Serialize(OldValues, serializerOptions)
          : Empty,
        NewValues = NewValues.Count != 0
          ? JsonSerializer.Serialize(NewValues, serializerOptions)
          : Empty,
        Modification = State,
      };
  }
}
